import { Task } from '../models/index.js';

export const seedTasks = async () => {
  const list = [
    { title: 'Find the Largest Number Without max()', description: 'Write a program that determines the maximum integer in a collection without using built-in max() helper.', instructions: 'Iterate through the array, initialize a maximum tracker to the first element, and compare each subsequent item.', difficulty: 'Easy', category: 'Python', xpReward: 50, deadline: 'Tomorrow', submissionType: 'code' },
    { title: 'Palindrome String Verifier', description: 'Check if a given string reads the same backwards as forwards, ignoring spaces and capitalization.', instructions: 'Filter non-alphanumeric characters, convert to lowercase, and check if reversed equals original.', difficulty: 'Easy', category: 'Python', xpReward: 50, deadline: 'In 2 days', submissionType: 'code' },
    { title: 'List Duplicate Remover', description: 'Given a list containing duplicate values, remove duplicates while preserving original order.', instructions: 'Use a seen set while appending to a results array.', difficulty: 'Easy', category: 'Python', xpReward: 50, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Character Frequency Counter', description: 'Count occurrences of each character in an input string and return the result formatted as a dictionary.', instructions: 'Use a hash map or dictionary loop.', difficulty: 'Easy', category: 'Python', xpReward: 50, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Two Sum Problem', description: 'Given an array of integers and a target sum, find the indices of the two numbers that add up to target.', instructions: 'Use a hash table mapping number to its index for O(n) single-pass lookup.', difficulty: 'Medium', category: 'DSA', xpReward: 100, deadline: 'In 3 days', submissionType: 'code' },
    { title: 'Reverse a Singly Linked List', description: 'Reverse the node pointers of a singly linked list in-place.', instructions: 'Maintain prev, current, and next pointers while traversing the list.', difficulty: 'Medium', category: 'DSA', xpReward: 100, deadline: 'In 4 days', submissionType: 'code' },
    { title: 'Valid Parentheses Checker', description: 'Given a string containing parentheses, brackets, and braces, determine if the input string is valid.', instructions: 'Push opening brackets to a stack, and pop to check corresponding match for closing brackets.', difficulty: 'Medium', category: 'DSA', xpReward: 100, deadline: 'In 5 days', submissionType: 'code' },
    { title: 'Merge Two Sorted Arrays', description: 'Merge two sorted arrays into one single sorted array in O(n + m) time.', instructions: 'Use two pointers comparing elements from each array.', difficulty: 'Easy', category: 'DSA', xpReward: 60, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Build a Semantic Card Component in HTML/CSS', description: 'Create a responsive developer profile card using clean HTML5 tags and CSS flexbox.', instructions: 'Include avatar, name, badges, and action buttons with responsive breakpoints.', difficulty: 'Easy', category: 'Web Dev', xpReward: 50, deadline: 'In 3 days', submissionType: 'code' },
    { title: 'Implement a Debounced Search Input', description: 'Write a JavaScript debounce function that delays API fetch until the user stops typing for 300ms.', instructions: 'Use setTimeout and clearTimeout inside a closure.', difficulty: 'Medium', category: 'Web Dev', xpReward: 90, deadline: 'In 4 days', submissionType: 'code' },
    { title: 'Dark Mode Switcher with localStorage', description: 'Create a theme toggle button that toggles a dark class and persists user preference.', instructions: 'Check localStorage on load and write back on toggle.', difficulty: 'Easy', category: 'Web Dev', xpReward: 60, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Fetch and Render User Data from REST API', description: 'Use async/await fetch() to pull JSON data and render cards dynamically into the DOM.', instructions: 'Handle loading state and network error try/catch blocks.', difficulty: 'Medium', category: 'Web Dev', xpReward: 80, deadline: 'In 6 days', submissionType: 'code' },
    { title: 'Build a Reusable Modal Component in React', description: 'Create an accessible dialog modal with backdrop click close and keyboard Escape listener.', instructions: 'Use React portals or absolute overlay with escape keydown listener.', difficulty: 'Medium', category: 'React', xpReward: 100, deadline: 'In 5 days', submissionType: 'code' },
    { title: 'Implement useCountdown Custom Hook', description: 'Create a custom hook that accepts seconds and returns current countdown, isRunning, and reset().', instructions: 'Use useEffect with setInterval and cleanup callback.', difficulty: 'Medium', category: 'React', xpReward: 90, deadline: 'Flexible', submissionType: 'code' },
    { title: 'React Todo List with Filtering', description: 'Build a stateful task list with All, Active, and Completed filters.', instructions: 'Store items in state array and derive filtered items using useMemo.', difficulty: 'Easy', category: 'React', xpReward: 70, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Paginated Table Component', description: 'Render a table displaying 10 rows per page with Next, Prev, and Page Number navigation.', instructions: 'Slice dataset based on currentPage and rowsPerPage state.', difficulty: 'Medium', category: 'React', xpReward: 100, deadline: 'In 1 week', submissionType: 'code' },
    { title: 'Express JWT Authorization Middleware', description: 'Write middleware that extracts Bearer token, verifies via jwt.verify, and appends req.user.', instructions: 'Return 401 if missing or invalid, next() if valid.', difficulty: 'Medium', category: 'Backend', xpReward: 100, deadline: 'In 4 days', submissionType: 'code' },
    { title: 'Rate Limiter Middleware from Scratch', description: 'Implement an in-memory IP rate limiter permitting max 60 requests per minute per IP.', instructions: 'Track timestamp windows per IP in a Map and return 429 when threshold exceeded.', difficulty: 'Hard', category: 'Backend', xpReward: 150, deadline: 'In 1 week', submissionType: 'code' },
    { title: 'Secure Password Validation Regex', description: 'Validate passwords containing at least 8 characters, 1 uppercase, 1 lowercase, 1 number, and 1 symbol.', instructions: 'Test string against regex assertions.', difficulty: 'Easy', category: 'Backend', xpReward: 50, deadline: 'Flexible', submissionType: 'code' },
    { title: 'Automated Database Health Check Endpoint', description: 'Create a /health API returning database ping latency, memory usage, and uptime.', instructions: 'Query process.uptime() and memoryUsage().', difficulty: 'Medium', category: 'Backend', xpReward: 80, deadline: 'Flexible', submissionType: 'code' }
  ];
  for (const t of list) {
    await Task.create(t);
  }
  console.log('✅ Created 20 Tasks');
};