import { Resource } from '../models/index.js';

export const seedResources = async () => {
  const list = [
    { title: 'Python 3 Quick Reference & Cheatsheet', description: 'Essential Python syntax, built-in functions, slicing, and common idioms in one printable guide.', category: 'Python', topic: 'Python', difficulty: 'Beginner', resourceType: 'pdf', url: 'https://docs.python.org/3/', tags: ['python', 'cheatsheet', 'basics'], xpReward: 30, duration: '10 min' },
    { title: 'Visual Guide to Python Data Structures', description: 'Understand lists, tuples, dictionaries, and sets with diagrams and runtime complexity tables.', category: 'Python', topic: 'Data Structures', difficulty: 'Beginner', resourceType: 'article', url: 'https://realpython.com/', tags: ['python', 'collections', 'visual'], xpReward: 40, duration: '15 min' },
    { title: 'Object-Oriented Python in 30 Minutes', description: 'A fast-paced video walk-through demonstrating classes, inheritance, properties, and composition.', category: 'Python', topic: 'OOP', difficulty: 'Intermediate', resourceType: 'video', url: 'https://www.youtube.com/', tags: ['python', 'oop', 'video'], xpReward: 50, duration: '28 min' },
    { title: 'Python File I/O & JSON Parsing Source Code', description: 'Sample code template demonstrating safe file context managers and structured JSON handling.', category: 'Python', topic: 'File Handling', difficulty: 'Beginner', resourceType: 'code', url: '', tags: ['python', 'json', 'io'], xpReward: 35, duration: '12 min' },
    { title: 'Big-O Complexity Chart & Cheat Sheet', description: 'Full visual breakdown of time and space complexities for sorting, searching, and tree traversals.', category: 'DSA', topic: 'Big-O', difficulty: 'Beginner', resourceType: 'pdf', url: 'https://www.bigocheatsheet.com/', tags: ['dsa', 'complexity', 'reference'], xpReward: 30, duration: '10 min' },
    { title: 'Two-Pointer Technique Masterclass', description: 'How to solve array problems in O(n) time using opposite and same-direction two-pointer patterns.', category: 'DSA', topic: 'Arrays', difficulty: 'Intermediate', resourceType: 'article', url: 'https://leetcode.com/explore/', tags: ['dsa', 'arrays', 'pointers'], xpReward: 45, duration: '20 min' },
    { title: 'Binary Search Demystified Video', description: 'Step-by-step video visualization of binary search boundaries and edge case prevention.', category: 'DSA', topic: 'Searching', difficulty: 'Intermediate', resourceType: 'video', url: 'https://www.youtube.com/', tags: ['dsa', 'search', 'algorithms'], xpReward: 50, duration: '22 min' },
    { title: 'Graph Traversal Patterns (BFS & DFS)', description: 'Comprehensive notes with pseudocode, recursion trees, and adjacency list representations.', category: 'DSA', topic: 'Graphs', difficulty: 'Advanced', resourceType: 'notes', url: '', tags: ['graphs', 'bfs', 'dfs', 'trees'], xpReward: 60, duration: '25 min' },
    { title: 'Modern HTML5 Semantic Tags Reference', description: 'Clean architecture guide for semantic layout tags: main, section, article, nav, and aside.', category: 'Web Dev', topic: 'HTML5', difficulty: 'Beginner', resourceType: 'article', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', tags: ['html5', 'semantics', 'web'], xpReward: 25, duration: '10 min' },
    { title: 'CSS Flexbox & Grid Interactive Cheatsheet', description: 'Printable layout reference with flex-direction, align-items, justify-content, and grid-template.', category: 'Web Dev', topic: 'CSS', difficulty: 'Beginner', resourceType: 'pdf', url: 'https://css-tricks.com/', tags: ['css', 'flexbox', 'grid'], xpReward: 35, duration: '15 min' },
    { title: 'JavaScript ES6+ Features Deep Dive', description: 'Arrow functions, destructuring, rest/spread, optional chaining, and nullish coalescing explained.', category: 'Web Dev', topic: 'JavaScript', difficulty: 'Intermediate', resourceType: 'notes', url: 'https://javascript.info/', tags: ['javascript', 'es6', 'syntax'], xpReward: 40, duration: '18 min' },
    { title: 'Asynchronous JavaScript & Promises Walkthrough', description: 'Deep-dive video into the JavaScript Event Loop, microtask queue, Promises, and async/await.', category: 'Web Dev', topic: 'JavaScript', difficulty: 'Intermediate', resourceType: 'video', url: 'https://www.youtube.com/', tags: ['js', 'async', 'promises'], xpReward: 50, duration: '30 min' },
    { title: 'React 18 Hooks Cheat Sheet', description: 'Quick syntax reference for useState, useEffect, useContext, useReducer, useMemo, and useRef.', category: 'React', topic: 'React', difficulty: 'Intermediate', resourceType: 'pdf', url: 'https://react.dev/', tags: ['react', 'hooks', 'cheatsheet'], xpReward: 40, duration: '12 min' },
    { title: 'Thinking in React Components', description: 'Step-by-step methodology for breaking UI mockups into clean, decoupled React component trees.', category: 'React', topic: 'Architecture', difficulty: 'Beginner', resourceType: 'article', url: 'https://react.dev/learn/thinking-in-react', tags: ['react', 'architecture', 'design'], xpReward: 35, duration: '15 min' },
    { title: 'React Context API vs Redux in 2026', description: 'When to use lightweight React Context and when dedicated state libraries are required.', category: 'React', topic: 'State Management', difficulty: 'Intermediate', resourceType: 'notes', url: '', tags: ['react', 'context', 'state'], xpReward: 45, duration: '20 min' },
    { title: 'Custom React Hooks Code Repository', description: 'Battle-tested hooks for useLocalStorage, useDebounce, useWindowSize, and useFetch.', category: 'React', topic: 'Hooks', difficulty: 'Advanced', resourceType: 'code', url: 'https://github.com/', tags: ['react', 'custom-hooks', 'code'], xpReward: 55, duration: '25 min' },
    { title: 'Node.js & Express REST API Architecture Guide', description: 'Best practices for organizing routes, controllers, middleware, and database models cleanly.', category: 'Backend', topic: 'Node.js', difficulty: 'Intermediate', resourceType: 'article', url: 'https://expressjs.com/', tags: ['node', 'express', 'api'], xpReward: 45, duration: '20 min' },
    { title: 'MongoDB Indexing & Query Optimization PDF', description: 'How compound indexes, query execution plans, and projection speed up database operations.', category: 'Backend', topic: 'MongoDB', difficulty: 'Advanced', resourceType: 'pdf', url: 'https://www.mongodb.com/docs/', tags: ['mongodb', 'indexes', 'performance'], xpReward: 50, duration: '22 min' },
    { title: 'JWT Authentication & Security Best Practices', description: 'Protecting routes, preventing XSS/CSRF, managing token lifespans, and password hashing with bcrypt.', category: 'Backend', topic: 'Security', difficulty: 'Advanced', resourceType: 'notes', url: 'https://owasp.org/', tags: ['jwt', 'security', 'auth'], xpReward: 60, duration: '25 min' },
    { title: 'Building Scalable APIs: Architecture Guide', description: 'High-level architectural video detailing API gateways, caching with Redis, and load balancing.', category: 'Backend', topic: 'System Design', difficulty: 'Advanced', resourceType: 'video', url: 'https://www.youtube.com/', tags: ['architecture', 'system-design', 'backend'], xpReward: 70, duration: '35 min' }
  ];
  for (const r of list) {
    await Resource.create({ ...r, isPublished: true });
  }
  console.log('✅ Created 20 Resources');
};